# ===================================================================
# COMMON
# ===================================================================
spring.application.name=cqrsStudy

# ===================================================================
# WRITE MODEL (MySQL - JPA)
# ===================================================================
spring.datasource.url=jdbc:mysql://localhost:3306/cqrs_study?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=user
spring.datasource.password=password
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# ===================================================================
# READ MODEL (Elasticsearch)
# ===================================================================
spring.elasticsearch.uris=http://localhost:9200